### ISSUE TITLE
Thoughts on SecureStorage for Android 10

### ISSUE THREAD

**Issue by govertbuijs** [wi3land/ionic-appauth-capacitor-demo#11]
Unfortunately the `cordova-plugin-secure-storage` plugin is no longer maintained.
There is a fork `cordova-plugin-secure-storage-echo`, but this doesn't seem to work on Android 10.
Likewise, the Capacitor secure plugin `capacitor-secure-storage-plugin` doesn't work on Android 10 (yet?).

Any thoughts on how to proceed with secure storage on Android 10?

**Comment by wi3land** [comment]
Hi I did have this in a previous iteration. however i rebuilt the demo from the ground up and forgot that change. this has now been added.

**Comment by govertbuijs** [comment]
Thanks, ionic-appauth is awesome!
