### ISSUE TITLE
App doesn't work in Capacitor after switching to Okta

### ISSUE THREAD

**Issue by mraible** [wi3land/ionic-appauth-capacitor-demo#2]
I tried forking this example and changing it to use Okta. You can see my changes in [this PR](https://github.com/mraible/ionic-appauth-capacitor-demo/pull/1).

To run it in Capacitor, I ran the following commands:

```
ionic capacitor add ios
npx cap open ios
```

I configured code signing and clicked Play to run the app. When the app starts, it crashes, and the following stack trace is in Xcode.

```
2019-04-12 23:02:29.658621-0600 App[23253:10271213] CAPKeyboard: resize mode - native
⚡️  Loading app at capacitor://localhost...
Reachable via WiFi
APP ACTIVE
⚡️  [log] - onscript loading complete
⚡️  [log] - Angular is running in the development mode. Call enableProdMode() to enable the production mode.
⚡️  [log] - Ionic Native: deviceready event fired after 210 ms
⚡️  To Native ->  App getLaunchUrl 68929190
⚡️  To Native ->  SplashScreen hide 68929191
⚡️  TO JS {}
⚡️  TO JS {}
To Native Cordova ->  SecureStorage init SecureStorage1930928562 ["options": [SecretStore]]
To Native Cordova ->  SecureStorage get SecureStorage1930928563 ["options": [SecretStore, token_response]]
2019-04-12 23:02:30.444659-0600 App[23253:10271300] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000113d856fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001114e4ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000113d85555 +[NSException raise:format:] + 197
	3   Foundation                          0x0000000110f13475 -[NSBundle initWithURL:] + 87
	4   Foundation                          0x0000000110f13524 +[NSBundle bundleWithURL:] + 45
	5   CordovaPlugins                      0x00000001102b7527 __34+[SAMKeychainQuery errorWithCode:]_block_invoke + 183
	6   libdispatch.dylib                   0x000000011b47adb5 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000011b47c83d _dispatch_once_callout + 66
	8   CordovaPlugins                      0x00000001102b6d6c +[S⚡️  To Native ->  App addListener 68929192
AMKeychainQuery errorWithCode:] + 156
	9   CordovaPlugins                      0x00000001102b6588 -[SAMKeychainQuery fetch:] + 568
	10  CordovaPlugins                      0x00000001102b8139 __21-[SecureStorage get:]_block_invoke + 169
	11  libdispatch.dylib                   0x000000011b479d7f _dispatch_call_block_and_release + 12
	12  libdispatch.dylib                   0x000000011b47adb5 _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x000000011b47d7b9 _dispatch_queue_override_invoke + 1022
	14  libdispatch.dylib                   0x000000011b48b632 _dispatch_root_queue_drain + 351
	15  libdispatch.dylib                   0x000000011b48bfca _dispatch_worker_thread2 + 130
	16  libsystem_pthread.dylib             0x000000011b8636b3 _pthread_wqthread + 583
	17  libsystem_pthread.dylib             0x000000011b8633fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by wi3land** [comment]
Hi I really need to make some documentation for these demos. I am using capacitors App feature instead of custom URL schemes in the capacitor demo. I never ran it on iOS as I didn't have a Mac to hand. 

Apparently on iOS you need to configure the info.plist URL scheme yourself. Capacitor does not add this in automatically like they do on Android. 

Please see the URL below for more info on what needs to be done.
https://capacitor.ionicframework.com/docs/apis/app

**Comment by mraible** [comment]
I tried running it on Android using:

```
ionic capacitor add android
```

Followed by:

```
npx cap open android
```

I clicked play in Android Studio, selected my Pixel 2 AVD (Android 9, API 28), and waited. The app loads, but when I click on "Sign in", nothing happens. The error in Android Studio is:

```
2019-04-13 09:44:23.963 5131-5284/com.appauth.demo E/Capacitor/Plugin/Console: ERROR Error: Uncaught (in promise): Error: Unable To Obtain Server Configuration
    Error: Unable To Obtain Server Configuration
        at AuthService.<anonymous> (http://localhost/vendor.js:88651:35)
        at step (http://localhost/vendor.js:88348:23)
        at Object.next (http://localhost/vendor.js:88329:53)
        at fulfilled (http://localhost/vendor.js:88320:58)
        at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost/polyfills.js:2749:26)
        at Object.onInvoke (http://localhost/vendor.js:53422:33)
        at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost/polyfills.js:2748:52)
        at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost/polyfills.js:2508:43)
        at http://localhost/polyfills.js:3247:34
        at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost/polyfills.js:2781:31)
```

Thinking the URL that it's trying to load is from a local server rather than my issuer URL, I tried:

```
ionic capacitor run android
```

Nope. Same error.

**Comment by wi3land** [comment]
AHH yeah I remember this error, as I'm using the angular requestor for capacitor cors comes into play. Capacitor runs on http://localhost with no port you will need to add this to your cors config in okta

**Comment by mraible** [comment]
Cool! I added http://localhost as a trusted origin and the app now opens Chrome when I click on Sign In. After I enter my credentials and click "Sign In", nothing happens. I tried adding the following to `android/app/build.gradle`, but it doesn't seem to help.

```
android.defaultConfig.manifestPlaceholders = [
    'appAuthRedirectScheme': 'com.oktapreview.dev-737523'
]
```

**Comment by wi3land** [comment]
For android you don't need to add the URL scheme in, capacitor does this for you, using the capacitor I'd. You can see it in the android manifest. Sorry I'm not at my computer atm so I can't provide code examples.

**Comment by mraible** [comment]
I tried changing `capacitor.config.json` to the following:

```json
{
  "appId": "com.okta.developer",
  "appName": "IonicOkta",
  "bundledWebRuntime": false,
  "webDir": "www"
}
```

Then I ran `rm -rf android` and:

```
ionic capacitor add android
npx cap open android
```

I said yes to upgrading when Android Studio prompted me. I added `com.okta.developer:/callback` as a login redirect URI and `com.okta.developer:/logout` as a logout redirect URI. The behavior remains the same: it doesn't redirect to the app after authenticating with Okta.

**Comment by wi3land** [comment]
Check your android manifest and make sure your URL scheme is in there and not the old one

**Comment by mraible** [comment]
It shows it has the new one:

![Screen Shot 2019-04-14 at 2 20 57 PM](https://user-images.githubusercontent.com/17892/56098728-8f27e900-5ec0-11e9-9d88-09dfc535bddb.png)

Here's the logs from Android Studio:

https://gist.githubusercontent.com/mraible/f79c62a506001fb52aa65144b67bcffc/raw/844e052f593b5f7dbd3c954c2fd8821415dcb59e/android.log

**Comment by wi3land** [comment]
I don't think this is an issue in the code as it follows the same code base as the Cordova app, bar the use of the getlaunchurl instead of the Cordova URL scheme stuff.

'''
if(this.platform.is('mobile') && !this.platform.is('mobileweb')){
      let appLaunchUrl : AppLaunchUrl = await App.getLaunchUrl();
      if(appLaunchUrl.url != undefined)
        this.handleCallback(appLaunchUrl.url);
    }
'''

The only thing I can advise is debug through or lay some console logs to see how far it gets before crashing.

I have tested this from an Android device without issue so it must be a compatibility issue. In which case this is a question to be answered by capacitor themselves as it is still only in beta.

I see that there is a section on the capacitor app docs for including a appRestoredResult on lower end devices when moving away from the webview, might be worth looking into.

https://capacitor.ionicframework.com/docs/apis/app/

**Comment by mraible** [comment]
I tried adding an "appStateChange" listener:

```ts
public async startUpAsync() {
  if(this.platform.is('mobile') && !this.platform.is('mobileweb')){
    let appLaunchUrl : AppLaunchUrl = await App.getLaunchUrl();
    console.log('launch URL', appLaunchUrl);
    if(appLaunchUrl.url != undefined) {
      this.handleCallback(appLaunchUrl.url);
    }
    App.addListener('appStateChange', (state: AppState) => {
      console.log('appStateChange', state);
    });
  }

  super.startUpAsync();
}
```

That reveals a bit more information:

```
2019-04-14 15:03:15.855 12219-12219/com.okta.developer V/Capacitor/Plugin/App: Notifying listeners for event appStateChange
2019-04-14 15:03:15.855 12219-12219/com.okta.developer D/Capacitor: App stopped
2019-04-14 15:03:15.857 12219-12219/com.okta.developer D/Capacitor: App destroyed
2019-04-14 15:03:15.880 12219-12219/com.okta.developer W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.f(PG:354)
        at org.chromium.android_webview.AwContents.a(PG:328)
        at org.chromium.android_webview.AwContents.a(PG:677)
        at com.android.webview.chromium.WebViewChromium.evaluateJavaScript(PG:290)
        at android.webkit.WebView.evaluateJavascript(WebView.java:1113)
        at com.getcapacitor.MessageHandler$1.run(MessageHandler.java:101)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-14 15:03:15.900 12219-12244/com.okta.developer W/cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=12247
2019-04-14 15:03:15.904 12219-12281/com.okta.developer D/EGL_emulation: eglMakeCurrent: 0xe634d1e0: ver 3 0 (tinfo 0xcda6ae20)
```

**Comment by mraible** [comment]
I was able to fix this by adding an `appUrlOpen` listener.

```
App.addListener('appUrlOpen', (data: AppUrlOpen) => {
  this.handleCallback(data.url);
});
```

I also had to change the custom scheme in `android/app/src/main/res/values/strings.xml` to use my reverse domain name:

```xml
<string name="custom_url_scheme">com.okta.dev-737523</string>
```

I also had to set the launchMode to singleTask so the URL does not trigger a new instance of the app in `android/app/src/main/AndroidManifest.xml`:

```xml
<activity
      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale"
      android:name="com.mydomain.app.MainActivity"
      android:label="@string/title_activity_main"
      android:launchMode="singleTask"
      android:theme="@style/AppTheme.NoActionBarLaunch">
```

It loads in iOS now, but has the following error when I click "Login".

```
⚡️  [error] - ERROR Error: Uncaught (in promise): Error: Unable To Obtain Server Configuration
capacitor://localhost/vendor.js:89259:44
step@capacitor://localhost/vendor.js:88956:27
fulfilled@capacitor://localhost/vendor.js:88928:62
onInvoke@capacitor://localhost/vendor.js:53422:39
run@capacitor://localhost/polyfills.js:2508:49
capacitor://localhost/polyfills.js:3247:37
onInvokeTask@capacitor://localhost/vendor.js:53413:43
runTask@capacitor://localhost/polyfills.js:2553:57
drainMicroTaskQueue@capacitor://localhost/polyfills.js:2959:42
invokeTask@capacitor://localhost/polyfills.js:2860:40
invokeTask@capacitor://localhost/polyfills.js:4102:20
globalZoneAwareCallback@capacitor://localhost/polyfills.js:4128:27
```

**Comment by wi3land** [comment]
Any error around being unable to obtain the serve configuration is due to the http handler not being able to connect to the server.

The main reasons for this could be cors issued or incorrect server url.

**Comment by mraible** [comment]
According to https://ionicframework.com/docs/faq/cors, it looks like Capacitor sends different `origin` headers for iOS and Android.


Platform | Origin
-- | --
iOS | capacitor://localhost
Android | http://localhost

Okta won't allow me to use `capacitor://localhost` as a Trusted Origin, so I tried the [HTTP workaround](https://ionicframework.com/docs/faq/cors#1-native-only-apps-ios-android-):

```
npm i cordova-plugin-advanced-http@2.0.9 @ionic-native/http@5.4.0
```

Unfortunately, this doesn't change anything and the error still happens. Is it possible to implement a new `Requestor` that uses `import { HTTP } from '@ionic-native/http/ngx'`?

**Comment by wi3land** [comment]
Use the Cordova requestor this uses @ionic-native/http but not the ngx implementation to keep it general so it can be used with react or vue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mraible** [comment]
That worked! I also found that I had to add my redirect scheme to the `ios/App/App/Info.plist`:

```
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLName</key>
    <string>com.getcapacitor.capacitor</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>capacitor</string>
      <string>com.oktapreview.dev-737523</string>
    </array>
  </dict>
</array>
```

Only strange behavior I'm seeing now is the token isn't displayed in the UI until I click on the screen (after I'm redirected back into the app).

**Comment by mraible** [comment]
I was able to solve the "click the screen" problem by using `ngZone.run()`.

```ts
public async startUpAsync() {
  if (this.platform.is('mobile') && !this.platform.is('mobileweb')) {
    App.addListener('appUrlOpen', (data: AppUrlOpen) => {
      this.ngZone.run(() => {
        this.handleCallback(data.url);
      });
    });
  }

  super.startUpAsync();
}
```

**Comment by mraible** [comment]
Thanks for all your help this past week @wi3land. 

FWIW, I used your examples to automate installing ionic-appauth into a new Ionic project. See https://github.com/oktadeveloper/schematics#ionic for more information. There's nothing Okta-specific in this, so `ng add @oktadev/schematics` should work with most OIDC providers (that support auth code flow + PKCE in the browser).

**Comment by wi3land** [comment]
I do plan on releasing vue/react Cordova/capacitor demos. so I'm sure we will be speaking again soon.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
