### ISSUE TITLE
Browser requests to the token endpoint may not include the offline_access scope.

### ISSUE THREAD

**Issue by danabradbury** [wi3land/ionic-appauth-capacitor-demo#22]
I am trying to run the sample app on both Android and in a browser, I am getting following error when trying login:

"message":"Http failure response for https://our-okta-server/oauth2/ausruqcv4uJD5x9xj0x6/v1/token: 400 OK",
"error":{"error":"invalid_scope","error_description":"Browser requests to the token endpoint may not include the offline_access scope."}}

For browser seems like this is expected, and I removed "offline_access", then login works as expected.  But then for Browser, how to handle access token expiration?  Is there a way to get a new access token if the session is still valid, without using refresh tokens?   My understanding is to use refresh tokens we need to include the "offline_access" in the list of scopes

For Android I also removed "offline_access" and login works, but I was thinking we should be able to use refresh tokens when build as an app?

Thanks,

Dana

**Comment by wi3land** [comment]
I think this is something to be directed at okta.
From previous conversations with Matt Raible at okta you cant do token refreshes from okta within the browser. But don't quote me on that.
