### ISSUE TITLE
IOS Simulator app is not navigating back to the app

### ISSUE THREAD

**Issue by IyyappanAmirthalingam** [wi3land/ionic-appauth-capacitor-demo#7]
Hi, 

When  I tried to ran the demo in IOS simulator I am keeping getting the error "Safari cannot open the the page because the address is invalid" and after authenticating it is not navigating back to the app.

Thanks

**Comment by IyyappanAmirthalingam** [comment]
Sorry My Mistake. It's working fine after fixing the URLSchema. Thanks

**Comment by Nazirovich** [comment]
> Sorry My Mistake. It's working fine after fixing the URLSchema. Thanks

how did you fix this.. I am facing the same problem

**Comment by daudihusbands** [comment]
Any luck with this?

**Comment by mikecabana** [comment]
@Angusoft-India can you give some more details on what you did to fix this? Running into similar issues and not too familiar with iOS development.
