### ISSUE TITLE
IOS simulator CROS error

### ISSUE THREAD

**Issue by IyyappanAmirthalingam** [wi3land/ionic-appauth-capacitor-demo#9]
Hi,

OAuth Authentication is happening but the token url is being blocked with the following error message in the IOS Simulator

Error: Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error"

Please help me if you have any idea.

Thanks

**Comment by wi3land** [comment]
Please see  [this link](https://ionicframework.com/docs/faq/cors#solutions-for-cors-errors) to see if it fixes your issue

**Comment by wi3land** [comment]
Can you let me know if the link helped your issue?
